//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_Cource_1_02
{
    using System;
    using System.Collections.Generic;
    
    public partial class TripRecord
    {
        public int Id { get; set; }
        public int CampingTripId { get; set; }
        public int CampingPlaceId { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public string Comments { get; set; }
    
        public virtual CampingPlace CampingPlace { get; set; }
        public virtual CampingTrip CampingTrip { get; set; }
    }
}
