//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_Cource_1_03_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampingTrip
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CampingTrip()
        {
            this.TouristCampingTripInfoes = new HashSet<TouristCampingTripInfo>();
            this.TripRecords = new HashSet<TripRecord>();
        }
    
        public int Id { get; set; }
        public int CampingRouteId { get; set; }
        public int TouristMinLevelId { get; set; }
        public int InstructorId { get; set; }
        public int ActivityTypeId { get; set; }
        public bool IsPlanned { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
    
        public virtual ActivityType ActivityType { get; set; }
        public virtual CampingRoute CampingRoute { get; set; }
        public virtual Tourist Tourist { get; set; }
        public virtual TouristLevel TouristLevel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TouristCampingTripInfo> TouristCampingTripInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TripRecord> TripRecords { get; set; }
    }
}
