//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_Cource_1_03_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampingRoutePlaceInfo
    {
        public int Id { get; set; }
        public int CampingRouteId { get; set; }
        public int CampingPlaceId { get; set; }
    
        public virtual CampingPlace CampingPlace { get; set; }
        public virtual CampingRoute CampingRoute { get; set; }
    }
}
