//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_Cource_1_03_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TouristAssigment
    {
        public int Id { get; set; }
        public int TouristId { get; set; }
        public Nullable<int> TouristPostId { get; set; }
        public Nullable<int> SectionId { get; set; }
        public Nullable<int> TouristLevelId { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    
        public virtual Section Section { get; set; }
        public virtual Tourist Tourist { get; set; }
        public virtual TouristPost TouristPost { get; set; }
        public virtual TouristLevel TouristLevel { get; set; }
    }
}
