//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_Cource_1_03_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Training
    {
        public int Id { get; set; }
        public int ScheduleId { get; set; }
        public int PeopleCame { get; set; }
        public bool IsHappen { get; set; }
        public int GroupId { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual Schedule Schedule { get; set; }
    }
}
